// const {number2text} = require('src/number')

//const {number2text} = require("arajs/src/number");
import { a1 } from "Testing.js";

//const  number  =  232;

console.log('Hello');
a1();

//console.log(number2text(number)); // مئتان و إثنان و ثلاثون

//const  text  =  'مَرْحَبًا بِكُمْ';

//const  strippedText  =  stripTashkeel(text);

//console.log(strippedText); // مرحبا بكم

//function translateToArabic() {

//};

